version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - prod-deps-{{ checksum "requirements.txt" }}
            - dev-deps-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r dev-requirements.txt
      - save_cache:
          key: prod-deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - save_cache:
          key: dev-deps-{{ checksum "dev-requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            ~/project/venv/bin/coverage run -m pytest tests/
            ~/project/venv/bin/coverage report
            ~/project/venv/bin/coverage xml
      - store_test_results:
          path: "coverage.xml"

workflows:
  main:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
