version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - restore_cache:
          keys:
            - dev-deps-{{ checksum "dev-requirements.txt" }}
      - run:
          name: Install Dev Dependencies
          command: |
            pip install -r dev-requirements.txt
      - save_cache:
          key: dev-deps-{{ checksum "dev-requirements.txt" }}
          paths:
            - ~/.dev

      - run:
          name: Run tests
          command: |
            $HOME/.local/bin/coverage run -m pytest tests/
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage xml
      - store_test_results:
          path: coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
