version: 2.1

orbs:
  python: circleci/python@1.2.1
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install Python dev dependencies
          command: |
            pip install -r dev-requirements.txt
      - run:
          name: Run tests
          command: |
            $HOME/.local/bin/coverage run -m pytest
            $HOME/.local/bin/coverage report
            $HOME/.local/bin/coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - build-and-test
      - heroku/deploy-via-git:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
